export const SET_NUTRI = 'SET_NUTRI'
export const SET_NUTRITODAY = 'SET_NUTRITODAY'
export const SET_NUTRITYPEMEAL = 'SET_NUTRITYPEMEAL'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_FORGOTPASSWORD_REQUEST = 'USER_FORGOTPASSWORD_REQUEST'
export const USER_FORGOTPASSWORD_SUCCESS = 'USER_FORGOTPASSWORD_SUCCESS'
export const USER_FORGOTPASSWORD_FAIL = 'USER_FORGOTPASSWORD_FAIL'

export const USER_RESETPASSWORD_REQUEST = 'USER_RESETPASSWORD_REQUEST'
export const USER_RESETPASSWORD_SUCCESS = 'USER_RESETPASSWORD_SUCCESS'
export const USER_RESETPASSWORD_FAIL = 'USER_RESETPASSWORD_FAIL'

export const USER_ADD_BODYINDEX = 'USER_ADD_BODYINDEX'
export const USER_ADD_BODYINDEX_REQUEST = 'USER_ADD_BODYINDEX_REQUEST'
export const  ADD_BODYINDEX_FAIL = 'ADD_BODYINDEX_FAIL'

export const USER_ADD_GOALFREQUENCY = 'USER_ADD_GOALFREQUENCY'
export const USER_ADD_GOALFREQUENCY_REQUEST = 'USER_ADD_GOALFREQUENCY_REQUEST'
export const  ADD_GOALFREQUENCY_FAIL = 'ADD_GOALFREQUENCY_FAIL'

export const USER_UPDATEPERCENT = 'USER_UPDATEPERCENT'
export const USER_UPDATEPERCENT_REQUEST = 'USER_UPDATEPERCENT_REQUEST'
export const  UPDATEPERCENT_FAIL = 'UPDATEPERCENT_FAIL'

export const USER_GETBODYINDEX = 'USER_GETBODYINDEX'
export const USER_GETBODYINDEX_REQUEST = 'USER_GETBODYINDEX_REQUEST'
export const  GETBODYINDEX_FAIL = 'GETBODYINDEX_FAIL'

export const USER_CREATEMENU = 'USER_CREATEMENU'
export const USER_CREATEMENU_REQUEST = 'USER_CREATEMENU_REQUEST'
export const  CREATEMENU_FAIL = 'CREATEMENU_FAIL'

export const USER_UPDATEMENU = 'USER_UPDATEMENU'
export const USER_UPDATEMENU_REQUEST = 'USER_UPDATEMENU_REQUEST'
export const  UPDATEMENU_FAIL = 'UPDATEMENU_FAIL'

export const USER_DELETEMENU = 'USER_DELETEMENU'
export const USER_DELETEMENU_REQUEST = 'USER_DELETEMENU_REQUEST'
export const  DELETEMENU_FAIL = 'DELETEMENU_FAIL'

export const USER_GETMENU = 'USER_GETMENU'
export const USER_GETMENU_REQUEST = 'USER_GETMENU_REQUEST'
export const  GETMENU_FAIL = 'GETMENU_FAIL'

export const USER_GETTYPEFOOD = 'USER_GETTYPEFOOD'
export const USER_GETTYPEFOOD_REQUEST = 'USER_GETTYPEFOOD_REQUEST'
export const  GETTYPEFOOD_FAIL = 'GETTYPEFOOD_FAIL'

export const USER_CREATEFOOD = 'USER_CREATEFOOD'
export const USER_CREATEFOOD_REQUEST = 'USER_CREATEFOOD_REQUEST'
export const  CREATEFOOD_FAIL = 'CREATEFOOD_FAIL'

export const USER_UPDATEFOOD = 'USER_UPDATEFOOD'
export const USER_UPDATEFOOD_REQUEST = 'USER_UPDATEFOOD_REQUEST'
export const  UPDATEFOOD_FAIL = 'UPDATEFOOD_FAIL'

export const USER_DELETEFOOD = 'USER_DELETEFOOD'
export const USER_DELETEFOOD_REQUEST = 'USER_DELETEFOOD_REQUEST'
export const  DELETEFOOD_FAIL = 'DELETEFOOD_FAIL'

export const USER_GETFOOD = 'USER_GETFOOD'
export const USER_GETFOOD_REQUEST = 'USER_GETFOOD_REQUEST'
export const  GETFOOD_FAIL = 'GETFOOD_FAIL'

export const USER_CREATEMEAL = 'USER_CREATEMEAL'
export const USER_CREATEMEAL_REQUEST = 'USER_CREATEMEAL_REQUEST'
export const  CREATEMEAL_FAIL = 'CREATEMEAL_FAIL'

export const USER_DELETEMEAL = 'USER_DELETEMEAL'
export const USER_DELETEMEAL_REQUEST = 'USER_DELETEMEAL_REQUEST'
export const  DELETEMEAL_FAIL = 'DELETEMEAL_FAIL'

export const USER_GETMEAL = 'USER_GETMEAL'
export const USER_GETMEAL_REQUEST = 'USER_GETMEAL_REQUEST'
export const  GETMEAL_FAIL = 'GETMEAL_FAIL'

export const USER_GETHISTORYWEIGHT = 'USER_GETHISTORYWEIGHT'
export const USER_GETHISTORYWEIGHT_REQUEST = 'USER_GETHISTORYWEIGHT_REQUEST'
export const  GETHISTORYWEIGHT_FAIL = 'GETHISTORYWEIGHT_FAIL'

export const USER_CREATETASK = 'USER_CREATETASK'
export const USER_CREATETASK_REQUEST = 'USER_CREATETASK_REQUEST'
export const  CREATETASK_FAIL = 'CREATETASK_FAIL'

export const USER_GETTASK = 'USER_GETTASK'
export const USER_GETTASK_REQUEST = 'USER_GETTASK_REQUEST'
export const  GETTASK_FAIL = 'GETTASK_FAIL'

export const USER_DELETETASK = 'USER_DELETETASK'
export const USER_DELETETASK_REQUEST = 'USER_DELETETASK_REQUEST'
export const  DELETETASK_FAIL = 'DELETETASK_FAIL'


export const USER_CHECKEDTASK = 'USER_CHECKEDTASK'
export const USER_CHECKEDTASK_REQUEST = 'USER_CHECKEDTASK_REQUEST'
export const  CHECKEDTASK_FAIL = 'CHECKEDTASK_FAIL'