export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_FORGOTPASSWORD_REQUEST = 'USER_FORGOTPASSWORD_REQUEST'
export const USER_FORGOTPASSWORD_SUCCESS = 'USER_FORGOTPASSWORD_SUCCESS'
export const USER_FORGOTPASSWORD_FAIL = 'USER_FORGOTPASSWORD_FAIL'

export const USER_RESETPASSWORD_REQUEST = 'USER_RESETPASSWORD_REQUEST'
export const USER_RESETPASSWORD_SUCCESS = 'USER_RESETPASSWORD_SUCCESS'
export const USER_RESETPASSWORD_FAIL = 'USER_RESETPASSWORD_FAIL'

export const USER_ADD_BODYINDEX = 'USER_ADD_BODYINDEX'
export const USER_ADD_BODYINDEX_REQUEST = 'USER_ADD_BODYINDEX_REQUEST'
export const  ADD_BODYINDEX_FAIL = 'ADD_BODYINDEX_FAIL'

export const USER_ADD_GOALFREQUENCY = 'USER_ADD_GOALFREQUENCY'
export const USER_ADD_GOALFREQUENCY_REQUEST = 'USER_ADD_GOALFREQUENCY_REQUEST'
export const  ADD_GOALFREQUENCY_FAIL = 'ADD_GOALFREQUENCY_FAIL'

export const USER_UPDATEPERCENT = 'USER_UPDATEPERCENT'
export const USER_UPDATEPERCENT_REQUEST = 'USER_UPDATEPERCENT_REQUEST'
export const  UPDATEPERCENT_FAIL = 'UPDATEPERCENT_FAIL'

export const USER_GETBODYINDEX = 'USER_GETBODYINDEX'
export const USER_GETBODYINDEX_REQUEST = 'USER_GETBODYINDEX_REQUEST'
export const  GETBODYINDEX_FAIL = 'GETBODYINDEX_FAIL'