export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_FORGOTPASSWORD_REQUEST = 'USER_FORGOTPASSWORD_REQUEST'
export const USER_FORGOTPASSWORD_SUCCESS = 'USER_FORGOTPASSWORD_SUCCESS'
export const USER_FORGOTPASSWORD_FAIL = 'USER_FORGOTPASSWORD_FAIL'

export const USER_RESETPASSWORD_REQUEST = 'USER_RESETPASSWORD_REQUEST,'
export const USER_RESETPASSWORD_SUCCESS = '  USER_RESETPASSWORD_SUCCESS,'
export const USER_RESETPASSWORD_FAIL = '  USER_RESETPASSWORD_FAIL,'